import { PageHero } from '../components/Page';
import { HomeAction } from '../components/home/HomeUI';

export const metadata = { title: 'Learn about monitoring at home', description: 'Practical guides to CGM, home blood-pressure monitoring and stroke awareness.' };

export default function Learn() {
  return <main><PageHero eyebrow="LEARN WITH HOMECLINICSTORE" title="Understand a little more. Choose with confidence.">Practical starting points for conversations with your healthcare professional.</PageHero><div className="hcs-wrap">
    <article id="glucose" className="store-learn-article"><span className="hcs-eyebrow">DIABETES & GLUCOSE</span><h2>What to know before choosing CGM.</h2><p>Continuous glucose monitoring provides a series of glucose estimates over time, helping you see patterns rather than a single moment. CGM sensors measure glucose in the fluid between cells, which is different from directly measuring a blood sample.</p><p>Choosing a system is also a practical decision. Ask about the sensor wear period, the phone and app you will need, replacement sensor costs, and what local support is available. Make sure you know how your healthcare professional wants you to use the information.</p><ul><li>Confirm that the exact device is suitable for the intended user.</li><li>Check the instructions for when an additional blood-glucose check may be needed.</li><li>Ask how alerts work and which app features are available locally.</li></ul><p>Follow your agreed care plan. Do not make treatment changes based on this general guide.</p><a className="textLink" href="https://www.niddk.nih.gov/health-information/diabetes/overview/managing-diabetes/continuous-glucose-monitoring">Read NIDDK’s guide to continuous glucose monitoring ↗</a><div className="actions"><HomeAction href="/shop/yuwell-cgm">Explore Yuwell Anytime CT3</HomeAction></div></article>
    <article id="blood-pressure" className="store-learn-article"><span className="hcs-eyebrow">HEART & BLOOD PRESSURE</span><h2>A better start to home measurements.</h2><p>An automatic, validated upper-arm monitor with the correct cuff size is a useful starting point for home blood-pressure monitoring. Ask your healthcare professional to check your technique and agree when to measure.</p><ul><li>Check the cuff’s size range against the circumference of your upper arm.</li><li>Sit with your back supported, feet flat and arm supported at heart level.</li><li>Record readings consistently and bring them to your healthcare appointments.</li></ul><p>Home monitoring does not replace clinical care. Keep taking prescribed treatment unless your healthcare professional advises otherwise. Pregnancy and children may require devices validated for those specific users.</p><a className="textLink" href="https://www.heart.org/en/health-topics/high-blood-pressure/understanding-blood-pressure-readings/monitoring-your-blood-pressure-at-home">Read the American Heart Association’s home-monitoring guide ↗</a><div className="actions"><HomeAction href="/shop/yuwell-blood-pressure">Explore blood-pressure monitoring</HomeAction></div></article>
    <article id="stroke-awareness" className="store-learn-article"><span className="hcs-eyebrow">STROKE AWARENESS</span><h2>Know when a reading is not enough.</h2><p>Sudden face drooping, weakness in an arm or difficulty speaking can be signs of a stroke. Seek emergency medical help immediately if a stroke is suspected, even if symptoms improve.</p><p>Do not wait for a device reading, an online enquiry or a routine care-team response. HomeClinicStore and the CareGrid preview are not emergency services.</p><p>For longer-term risk discussions, talk with your healthcare professional about blood pressure and other factors relevant to you. No home device can guarantee stroke prevention.</p><a className="textLink" href="https://www.heart.org/en/about-us/heart-attack-and-stroke-symptoms">Read the American Heart Association’s warning-sign guidance ↗</a></article>
  </div></main>;
}
