'use client';
import {useState} from 'react';
import {ArrowRight, CalendarDays, CheckCircle2, Download, Menu, Search, ShieldCheck, ShoppingBag, UserRound, X} from 'lucide-react';

type Modal = 'service'|'certificate'|'login'|null;
const products=[
 {name:'Yuwell Continuous Glucose Monitoring',desc:'Connected glucose monitoring for the home.',price:'R2,499',tag:'CGM'},
 {name:'Yuwell Blood Pressure Monitor',desc:'Home patient monitoring with a simple experience.',price:'R1,299',tag:'PATIENT MONITORING'},
 {name:'Yuwell Pulse Oximeter',desc:'Compact oxygen saturation and pulse monitoring.',price:'R699',tag:'PATIENT MONITORING'}
];
export default function Home(){
 const [modal,setModal]=useState<Modal>(null); const [sent,setSent]=useState(false); const [menu,setMenu]=useState(false);
 const nav=(id:string)=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'});
 return <>
 <header className="nav glass"><div className="container navinner"><a className="brand" href="#">homeclinic<span>store</span></a><nav className="navlinks"><a onClick={()=>nav('shop')}>Shop</a><a onClick={()=>nav('cgm')}>CGM</a><a onClick={()=>nav('monitoring')}>Patient Monitoring</a><a onClick={()=>nav('rpm')}>RPM</a><a onClick={()=>nav('services')}>Services</a><a onClick={()=>nav('support')}>Support</a></nav><div className="navactions"><button className="iconbtn" aria-label="Search"><Search size={17}/></button><button className="iconbtn" aria-label="Account" onClick={()=>setModal('login')}><UserRound size={17}/></button><button className="iconbtn" aria-label="Cart"><ShoppingBag size={17}/></button><button className="pill" onClick={()=>setModal('service')}>Book a Service</button><button className="iconbtn mobileMenu" onClick={()=>setMenu(!menu)} aria-label="Menu">{menu?<X size={18}/>:<Menu size={18}/>}</button></div></div>{menu&&<div className="container" style={{padding:'15px 0 20px'}}><div className="card" style={{display:'grid',gap:10}}>{['shop','cgm','monitoring','rpm','services','support'].map(x=><button key={x} className="link" onClick={()=>{nav(x);setMenu(false)}}>{x.toUpperCase()} <ArrowRight size={14}/></button>)}</div></div>}</header>
 <main>
 <section className="hero"><div className="container heroGrid"><div><div className="eyebrow">Connected home healthcare</div><h1>Better healthcare starts at home.</h1><p>Connected medical equipment, remote patient monitoring and professional biomedical support — designed around care at home.</p><div className="actions"><button className="pill" onClick={()=>nav('cgm')}>Explore CGM <ArrowRight size={15} style={{verticalAlign:'middle'}}/></button><button className="pill outline" onClick={()=>nav('monitoring')}>Patient Monitoring</button></div></div><div className="heroVisual"><div className="device"><div className="sensor"/></div><div className="floating f1"><b>CGM</b><br/><span className="muted">Connected glucose care</span></div><div className="floating f2"><b>RPM ready</b><br/><span className="muted">Home → provider</span></div></div></div></section>
 <section className="section" id="shop"><div className="container"><div className="sectionHead"><div><div className="eyebrow">Featured equipment</div><h2>Technology for care at home.</h2></div><p className="sub">Explore HCS-supported home medical equipment, led by Yuwell continuous glucose monitoring and patient-monitoring solutions.</p></div><div className="cards">{products.map((p,i)=><div className="card" key={p.name}><div className="productImage"><div className="productShape"/></div><span className="tag">{p.tag}</span><h3>{p.name}</h3><p className="muted">{p.desc}</p><div className="price">{p.price}</div><a className="link" href="#">View product <ArrowRight size={14}/></a></div>)}</div></div></section>
 <section className="section" id="cgm"><div className="container"><div className="feature"><div><div className="eyebrow">Flagship technology</div><h2>Smarter glucose monitoring.</h2><p className="sub">Explore Yuwell continuous glucose monitoring and connected home-care workflows. Product specifications and clinical claims should be populated from approved HCS/Yuwell information.</p><div className="actions"><button className="pill">Explore Yuwell CGM</button><button className="pill outline">Shop CGM</button></div></div><div className="featureImage"><div className="device" style={{transform:'rotate(-6deg)'}}><div className="sensor"/></div></div></div></div></section>
 <section className="section" id="monitoring"><div className="container"><div className="feature dark"><div className="featureImage"><div className="monitor"><div className="screen"><span className="metric">BLOOD PRESSURE</span><span className="metric"><strong>122 / 78</strong></span><span className="metric">SpO₂</span><span className="metric"><strong>98%</strong></span></div></div></div><div><div className="eyebrow">Patient monitoring</div><h2>Monitor what matters.</h2><p style={{color:'#aeb5c0',lineHeight:1.7}}>Premium home patient-monitoring equipment designed around a simple experience, with support throughout the equipment lifecycle.</p><div className="actions"><button className="pill" style={{background:'#fff',color:'#111'}}>Explore monitoring <ArrowRight size={15} style={{verticalAlign:'middle'}}/></button></div></div></div></div></section>
 <section className="section" id="rpm"><div className="container"><div className="sectionHead"><div><div className="eyebrow">Remote patient monitoring</div><h2>Your health. Connected.</h2></div><p className="sub">Connect suitable home medical devices, patient readings and healthcare workflows through an RPM architecture built for connected care.</p></div><div className="rpmflow"><div className="flow">Patient<br/><span className="muted">At home</span></div><div className="flow">Medical Device<br/><span className="muted">Measure</span></div><div className="flow">HCS RPM<br/><span className="muted">Connect</span></div><div className="flow">Provider<br/><span className="muted">Monitor</span></div></div></div></section>
 <section className="section" id="services"><div className="container"><div className="sectionHead"><div><div className="eyebrow">Biomedical services</div><h2>Keep your equipment performing.</h2></div><p className="sub">Professional biomedical services specifically for supported home medical equipment.</p></div><div className="cards">{[['Calibration','Book calibration online and access your certificate digitally.'],['Preventative maintenance','Maintain supported equipment and identify potential issues early.'],['Repair & inspection','Request troubleshooting, repair and performance assessment.']].map(([t,d])=><div className="card" key={t}><ShieldCheck size={26}/><h3 style={{marginTop:22}}>{t}</h3><p className="muted">{d}</p><button className="link" onClick={()=>setModal('service')}>{t==='Calibration'?'Book calibration':'Request service'} <ArrowRight size={14}/></button></div>)}</div></div></section>
 <section className="section" id="support"><div className="container"><div className="feature"><div><div className="eyebrow">Digital records</div><h2>Your certificates. Always within reach.</h2><p className="sub">Book calibration online, track service progress and download approved digital certificates from your HCS account.</p><div className="actions"><button className="pill" onClick={()=>setModal('service')}><CalendarDays size={15} style={{verticalAlign:'middle'}}/> Book calibration</button><button className="pill outline" onClick={()=>setModal('certificate')}>Verify certificate</button></div></div><div className="card"><CheckCircle2 size={28}/><h3 style={{marginTop:20}}>HCS-CAL-2026-000123</h3><p className="muted">Yuwell patient monitoring equipment</p><div className="actions"><button className="pill"><Download size={15} style={{verticalAlign:'middle'}}/> Download PDF</button></div></div></div></div></section>
 <section className="cta"><div className="container"><div className="ctaBox"><div className="eyebrow">HomeClinicStore</div><h2>Choose it. Connect it. Maintain it.</h2><p className="sub" style={{margin:'0 auto'}}>Home medical equipment, RPM and biomedical support in one connected experience.</p><div className="actions" style={{justifyContent:'center'}}><button className="pill" onClick={()=>nav('shop')}>Shop equipment</button><button className="pill outline" onClick={()=>setModal('service')}>Book a service</button></div></div></div></section>
 </main>
 <footer className="footer"><div className="container footerGrid"><div><div className="brand">homeclinic<span>store</span></div><p>Better healthcare starts at home.</p></div><div><h4>Shop</h4><a href="#cgm">CGM</a><a href="#monitoring">Patient Monitoring</a><a href="#shop">Home Equipment</a></div><div><h4>Services</h4><a href="#services">Calibration</a><a href="#services">Maintenance</a><a href="#services">Repair</a></div><div><h4>Support</h4><a href="#rpm">RPM</a><a href="#support">Certificates</a><a href="#">Contact HCS</a></div></div><div className="container" style={{marginTop:40}}>© 2026 HomeClinicStore. All rights reserved.</div></footer>
 {modal&&<div className="modal"><div className="modalBox"><button className="close" onClick={()=>{setModal(null);setSent(false)}}><X size={17}/></button>{modal==='login'?<><div className="eyebrow">My HCS</div><h2>Customer account</h2><p className="muted">A production implementation can connect this dashboard to secure authentication, orders, equipment, service history and certificates.</p><div className="form"><input placeholder="Email address"/><input placeholder="Password" type="password"/><button className="pill">Sign in</button></div></>:modal==='certificate'?<><div className="eyebrow">Certificate verification</div><h2>Verify a certificate.</h2><p className="muted">Enter a certificate number to check its status.</p><div className="form"><input placeholder="HCS-CAL-2026-000123"/><button className="pill" onClick={()=>setSent(true)}>Verify certificate</button></div>{sent&&<div className="success"><b>Certificate valid</b><br/>HCS-CAL-2026-000123 · Demo record</div>}</>:<><div className="eyebrow">Online service booking</div><h2>Book a service.</h2><p className="muted">Submit your equipment details. The live version can connect this workflow to availability, payments, technicians and certificate generation.</p><div className="form"><select><option>Calibration</option><option>Preventative Maintenance</option><option>Repair</option><option>Inspection</option></select><input placeholder="Manufacturer"/><input placeholder="Model"/><input placeholder="Serial number"/><input type="date"/><textarea placeholder="Tell us what you need..."/><button className="pill" onClick={()=>setSent(true)}>Confirm service request</button></div>{sent&&<div className="success"><b>Request received.</b><br/>Demo booking reference: HCS-SRV-2026-000124</div>}</>}</div></div>}
 </>;
}
