import { launch } from './launch';

export type CatalogProduct = {
  slug: string;
  name: string;
  category: string;
  copy: string;
  detail: string;
  icon: 'glucose' | 'pressure' | 'temperature' | 'oxygen' | 'respiratory' | 'scale' | 'fetal' | 'ecg';
  image?: string;
  priceHint?: number;
};

export const catalog: CatalogProduct[] = [
  {
    slug: 'yuwell-cgm',
    name: 'Yuwell Anytime CT-3 CGM',
    category: 'Manage diabetes',
    copy: 'Continuous glucose monitoring with a reusable transmitter and 14-day sensors. Real-time readings every 3 minutes via the Anytime app.',
    detail: '14-day sensor · Reusable transmitter up to 2 years · MARD ~6.9–9%',
    icon: 'glucose',
    image: '/images/products/yuwell-anytime-ct3.webp',
    priceHint: 2500,
  },
  {
    slug: 'yuwell-transmitter',
    name: 'Yuwell Anytime Transmitter',
    category: 'Manage diabetes',
    copy: 'Reusable CGM transmitter for the Anytime CT-3 system. Pairs with 14-day sensors for continuous glucose data.',
    detail: 'Up to 2-year life · Bluetooth · Charge via stand',
    icon: 'glucose',
    image: '/images/products/yuwell-transmitter.webp',
    priceHint: 1100,
  },
  {
    slug: 'yuwell-sensor',
    name: 'Yuwell Anytime Sensor (14-day)',
    category: 'Manage diabetes',
    copy: 'Sterile 14-day CGM sensor with auto-applicator. Requires a compatible Anytime transmitter.',
    detail: '14-day wear · No routine calibration · Water resistant',
    icon: 'glucose',
    image: '/images/products/yuwell-sensor.webp',
    priceHint: 950,
  },
  {
    slug: 'rossmax-z5',
    name: 'Rossmax Z5 Bluetooth BP Monitor (PARR)',
    category: 'Monitor blood pressure',
    copy: 'Clinically oriented upper-arm monitor with AFib, arrhythmia and premature contraction detection, Bluetooth app sync and rechargeable battery.',
    detail: 'PARR technology · USB-C · 120 memories · Cuff 24–40 cm',
    icon: 'pressure',
    image: '/images/products/rossmax-z5-bp.webp',
    priceHint: 2299,
  },
  {
    slug: 'rossmax-x5',
    name: 'Rossmax X5 BP Monitor (PARR)',
    category: 'Monitor blood pressure',
    copy: 'Accurate upper-arm blood pressure monitor with PARR stroke-risk screening, cuff detection and 7-day averaging.',
    detail: 'AFib / ARR detection · Large LCD · Cuff 24–40 cm',
    icon: 'pressure',
    image: '/images/products/rossmax-x5-bp.webp',
    priceHint: 1699,
  },
  {
    slug: 'bp-upper-arm',
    name: 'Upper-Arm Blood Pressure Monitor',
    category: 'Monitor blood pressure',
    copy: 'Reliable automatic upper-arm blood pressure monitoring for home and clinic routines.',
    detail: 'Exact model confirmed on enquiry · Cuff size to fit',
    icon: 'pressure',
    image: '/images/products/bp-upper-arm.webp',
    priceHint: 1199,
  },
  {
    slug: 'bp-wrist',
    name: 'Wrist Blood Pressure Monitor',
    category: 'Monitor blood pressure',
    copy: 'Compact wrist-worn blood pressure monitor for portable daily checks.',
    detail: 'Portable form factor · Exact model on enquiry',
    icon: 'pressure',
    image: '/images/products/bp-wrist.webp',
    priceHint: 999,
  },
  {
    slug: 'bp-bluetooth',
    name: 'Bluetooth Blood Pressure Monitor',
    category: 'Monitor blood pressure',
    copy: 'App-connected blood pressure monitoring so you can log and share readings with your care team.',
    detail: 'Bluetooth · App sync · Exact model on enquiry',
    icon: 'pressure',
    image: '/images/products/bp-bluetooth.webp',
    priceHint: 1899,
  },
  {
    slug: 'rossmax-sb210',
    name: 'Rossmax SB210 Pulse Oximeter (ACT)',
    category: 'Track daily vitals',
    copy: 'Fingertip SpO2 and pulse oximeter with Artery Check Technology and Bluetooth. Spot-check oxygen saturation and pulse rate in about a minute.',
    detail: 'ACT arterial condition · Bluetooth · OLED display',
    icon: 'oxygen',
    image: '/images/products/rossmax-sb210-spo2.webp',
    priceHint: 2299,
  },
  {
    slug: 'spo2-fingertip',
    name: 'Fingertip Pulse Oximeter',
    category: 'Track daily vitals',
    copy: 'Compact fingertip device for estimated oxygen saturation and pulse rate spot checks at home.',
    detail: 'SpO2 + pulse · Exact model on enquiry',
    icon: 'oxygen',
    image: '/images/products/spo2-fingertip.webp',
    priceHint: 699,
  },
  {
    slug: 'spo2-ring',
    name: 'SpO2 Ring Monitor',
    category: 'Track daily vitals',
    copy: 'Wearable ring-style monitor for oxygen saturation and pulse in a compact form factor.',
    detail: 'Wearable design · Exact model on enquiry',
    icon: 'oxygen',
    image: '/images/products/spo2-ring.webp',
    priceHint: 1499,
  },
  {
    slug: 'rossmax-hc700bt',
    name: 'Rossmax HC700BT Non-Contact Thermometer',
    category: 'Track daily vitals',
    copy: 'Telephoto non-contact thermometer for temple and object temperature in about one second, with Bluetooth.',
    detail: 'Up to 10 cm measurement · Bluetooth · Fever alarm',
    icon: 'temperature',
    image: '/images/products/thermometer-hc700.webp',
    priceHint: 1099,
  },
  {
    slug: 'rossmax-hs200',
    name: 'Rossmax HS200 Bluetooth Glucometer',
    category: 'Manage diabetes',
    copy: 'Fast blood glucose meter with GDH-FAD chemistry, small sample volume and Bluetooth app connectivity.',
    detail: '5-second test · 500 memories · Healthstyle app',
    icon: 'glucose',
    image: '/images/products/rossmax-hs200.webp',
    priceHint: 999,
  },
  {
    slug: 'glucose-strips',
    name: 'Glucose Test Strips (HS200)',
    category: 'Manage diabetes',
    copy: 'Compatible test strips for the Rossmax HS200 blood glucose monitoring system.',
    detail: 'Consumable · Pack size confirmed on quote',
    icon: 'glucose',
    image: '/images/products/glucose-strips.webp',
    priceHint: 349,
  },
  {
    slug: 'cpap',
    name: 'CPAP / PAP Therapy Device',
    category: 'Respiratory care',
    copy: 'Home continuous positive airway pressure systems for sleep apnoea and respiratory support. Exact model and mask kit confirmed on enquiry.',
    detail: 'Therapy device · Model and accessories on quote',
    icon: 'respiratory',
    image: '/images/products/cpap.webp',
    priceHint: 15000,
  },
  {
    slug: 'capnograph',
    name: 'Portable Capnograph',
    category: 'Respiratory care',
    copy: 'End-tidal CO2 monitoring for clinical and emergency use. Specifications confirmed on enquiry.',
    detail: 'EtCO2 monitoring · Professional device',
    icon: 'respiratory',
    image: '/images/products/capnograph.webp',
    priceHint: 12000,
  },
  {
    slug: 'scale-wb101',
    name: 'Digital Body Scale (WB101)',
    category: 'Track daily vitals',
    copy: 'Digital body weight scale for everyday home monitoring.',
    detail: 'Home scale · Exact model on enquiry',
    icon: 'scale',
    image: '/images/products/scale-wb101.webp',
    priceHint: 599,
  },
  {
    slug: 'baby-scale',
    name: 'Baby / Infant Scale',
    category: 'Track daily vitals',
    copy: 'Infant weighing scale for paediatric and home-care use.',
    detail: 'Paediatric capacity · Exact model on enquiry',
    icon: 'scale',
    image: '/images/products/baby-scale.webp',
    priceHint: 899,
  },
  {
    slug: 'fetal-doppler',
    name: 'Fetal Doppler / Baby Sound Monitor',
    category: 'Fetal & maternal',
    copy: 'Handheld fetal heart rate Doppler for antenatal monitoring under professional guidance.',
    detail: 'Portable Doppler · Exact model on enquiry',
    icon: 'fetal',
    image: '/images/products/fetal-doppler.webp',
    priceHint: 1299,
  },
  {
    slug: 'ecg-portable',
    name: 'Portable ECG',
    category: 'ECG & diagnostics',
    copy: 'Handheld electrocardiograph for spot ECG screening. Lead count and connectivity confirmed on enquiry.',
    detail: 'Handheld ECG · Specs on quote',
    icon: 'ecg',
    image: '/images/products/ecg-portable.webp',
    priceHint: 4500,
  },
];
