import Link from "next/link";
import { ArrowLeft, CheckCircle2, ShieldCheck, ShoppingBag, Wrench } from "lucide-react";

const data:Record<string,{name:string;category:string;price:number;description:string;features:string[]}> = {
 "yuwell-cgm":{name:"Yuwell Continuous Glucose Monitoring",category:"CGM",price:2499,description:"A premium home glucose-monitoring product experience for HCS. Populate final specifications, availability and approved product claims from HCS/Yuwell source material.",features:["Designed for home glucose monitoring","Digital-first product experience","Supported by HomeClinicStore","Service and support lifecycle"]},
 "yuwell-blood-pressure":{name:"Yuwell Blood Pressure Monitor",category:"Patient Monitoring",price:1299,description:"Home blood-pressure monitoring equipment presented through the HCS connected-care ecosystem.",features:["Simple home monitoring","HCS equipment support","Service and calibration workflow","Customer equipment history"]},
 "yuwell-pulse-oximeter":{name:"Yuwell Pulse Oximeter",category:"Patient Monitoring",price:699,description:"Compact patient-monitoring equipment for supported home-care workflows.",features:["Compact monitoring","HCS support","Service lifecycle","Digital records"]},
 "yuwell-thermometer":{name:"Yuwell Digital Thermometer",category:"Patient Monitoring",price:349,description:"Home temperature monitoring equipment with HCS support.",features:["Home monitoring","Easy-to-use experience","Support lifecycle","Digital service records"]}
};
export default async function ProductPage({params}:{params:Promise<{slug:string}>}) {
 const {slug}=await params; const p=data[slug]||data["yuwell-cgm"];
 return <><header className="nav glass"><div className="container navinner"><Link className="brand" href="/">homeclinic<span>store</span></Link><nav className="navlinks"><Link href="/shop">Shop</Link><Link href="/#cgm">CGM</Link><Link href="/#monitoring">Patient Monitoring</Link><Link href="/#rpm">RPM</Link><Link href="/#services">Services</Link></nav><div className="navactions"><Link className="pill" href="/shop"><ShoppingBag size={15}/> Shop</Link></div></div></header>
 <main><section className="productDetail"><div className="container"><Link className="backLink" href="/shop"><ArrowLeft size={15}/> Back to shop</Link><div className="productDetailGrid"><div className="productGallery"><div className="productHeroVisual"><div className={`visualDevice ${p.category==="CGM"?"cgmDevice":"monitorDevice"}`}>{p.category==="CGM"?<div className="visualSensor">CGM</div>:<div className="visualScreen"><span>HCS</span><b>122/78</b></div>}</div></div></div><div className="productInfo"><span className="tag">{p.category}</span><h1>{p.name}</h1><p className="productLead">{p.description}</p><div className="productPrice">R{p.price.toLocaleString("en-ZA")}</div><div className="actions"><button className="pill">Add to cart</button><button className="pill outline">Buy now</button></div><div className="productTrust"><span><ShieldCheck size={18}/> HCS support</span><span><Wrench size={18}/> Serviceable equipment</span></div><hr/><h3>Why HCS?</h3><div className="featureList">{p.features.map(x=><div key={x}><CheckCircle2 size={17}/>{x}</div>)}</div></div></div></div></section>
 <section className="section"><div className="container"><div className="feature"><div><div className="eyebrow">Beyond the purchase</div><h2>Supported throughout its lifecycle.</h2><p className="sub">Book calibration, preventative maintenance or repair for supported home medical equipment. Approved digital certificates can be accessed through the HCS service workflow.</p><div className="actions"><Link className="pill" href="/#services">Book a service <Wrench size={15}/></Link><Link className="pill outline" href="/#support">Certificates</Link></div></div><div className="card"><CheckCircle2 size={28}/><h3>HCS equipment support</h3><p className="muted">Service, calibration and digital records are part of the HCS ecosystem.</p></div></div></div></section></main></>
}
